spring:
  application:
    name: gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_ISSUER_URI:http://localhost:30900/realms/stockflow}
          jwk-set-uri: http://keycloak-cluster.stockflow.svc.cluster.local:8000/realms/stockflow/protocol/openid-connect/certs
  webflux:
    base-path: /
  cloud:
    consul:
      loadbalancer:
        health-check:
          enabled: true
      host: consul-node.stockflow.svc.cluster.local
      port: 8500
      discovery:
        query-passing: true
        register: true
        prefer-ip-address: true
        health-check-path: /actuator/health
        health-check-interval: 5s
        instance-id: ${spring.application.name}:${server.port}:${random.value[6]}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lowerCaseServiceId: true
          routes:
            - id: ocr
              uri: lb://ocr-api
              predicates:
                - Path=/api/ocr/**
              filters:
                - StripPrefix=2
            - id: stockflow
              uri: lb://stockflow
              predicates:
                - Path=/api/stockflow/**
              filters:
                - StripPrefix=2
            - id: keycloak-route
              uri: http://keycloak-cluster.stockflow.svc.cluster.local:8000
              predicates:
                - Path=/login/**
              filters:
                - StripPrefix=1

server:
  port: 9000
