apiVersion: v1
kind: Service
metadata:
  name: consul-node
  namespace: stockflow
spec:
  type: NodePort
  selector:
    app: consul
  ports:
    - name: http
      port: 8500
      targetPort: 8500
      nodePort: 30200
    - name: dns
      port: 8600
      targetPort: 8600

